/**
 * Pure helpers for `yarn brand:generate` (ADR-0023): where each icon goes,
 * at what size, and the small native files around them.
 */

/** Android densities and their scale factor against mdpi (1 dp = 1 px). */
export const ANDROID_DENSITIES = [
  { name: 'mdpi', scale: 1 },
  { name: 'hdpi', scale: 1.5 },
  { name: 'xhdpi', scale: 2 },
  { name: 'xxhdpi', scale: 3 },
  { name: 'xxxhdpi', scale: 4 },
] as const;

/** Legacy launcher icon (Android 7 and older): 48 dp. */
export const LEGACY_ICON_DP = 48;
/** Adaptive icon layers: 108 dp, of which a 66 dp circle is always visible. */
export const ADAPTIVE_LAYER_DP = 108;
/**
 * The emblem's share of an adaptive layer: its badge (97% of the SVG box)
 * then fills the 66 dp safe circle, so no launcher mask cuts it.
 */
export const ADAPTIVE_EMBLEM_SHARE = 0.63;
/** The emblem's share of the iOS icon square, inside the rounded-rect mask. */
export const IOS_EMBLEM_SHARE = 0.86;

/**
 * Hex colours from the design tokens (`src/shared/theme/tokens.ts`), read as
 * text so the scripts don't compile app code. The lookup throws on an unknown
 * name, so a renamed token fails loudly instead of producing a wrong colour.
 */
export function readPalette(tokensSource: string): (name: string) => string {
  const palette = new Map<string, string>();
  for (const [, name, hex] of tokensSource.matchAll(
    /(\w+): '(#[0-9A-Fa-f]{6})'/g,
  )) {
    if (name !== undefined && hex !== undefined) palette.set(name, hex);
  }
  return name => {
    const hex = palette.get(name);
    if (hex === undefined) throw new Error(`Palette entry not found: ${name}`);
    return hex;
  };
}

/** Android adaptive icon: brand background, emblem foreground, themed-icon layer. */
export const adaptiveIconXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by yarn brand:generate (ADR-0023). -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
</adaptive-icon>
`;

/** A one-colour Android resources file. */
export const colorResourceXml = (name: string, hex: string): string =>
  `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by yarn brand:generate (ADR-0023). -->
<resources>
    <color name="${name}">${hex}</color>
</resources>
`;

const component = (hex: string, offset: number): string =>
  (parseInt(hex.slice(offset, offset + 2), 16) / 255).toFixed(3);

const srgb = (hex: string) => ({
  'color-space': 'srgb',
  components: {
    red: component(hex, 1),
    green: component(hex, 3),
    blue: component(hex, 5),
    alpha: '1.000',
  },
});

const hasAppearance = (entry: unknown): boolean =>
  typeof entry === 'object' && entry !== null && 'appearances' in entry;

/**
 * An asset-catalog colour set (its parsed Contents.json) with a dark variant
 * added, replacing any earlier one. bootsplash writes the light colour; its
 * dark-mode generation needs a paid licence (ADR-0010).
 */
export function withDarkVariant(contents: object, darkHex: string): object {
  const colors: readonly unknown[] =
    'colors' in contents && Array.isArray(contents.colors)
      ? contents.colors
      : [];
  return {
    ...contents,
    colors: [
      ...colors.filter(entry => !hasAppearance(entry)),
      {
        appearances: [{ appearance: 'luminosity', value: 'dark' }],
        color: srgb(darkHex),
        idiom: 'universal',
      },
    ],
  };
}

/** iOS single-size app icon with its dark and tinted variants (iOS 18+). */
export const appIconContents = {
  images: [
    {
      filename: 'AppIcon.png',
      idiom: 'universal',
      platform: 'ios',
      size: '1024x1024',
    },
    {
      appearances: [{ appearance: 'luminosity', value: 'dark' }],
      filename: 'AppIcon-dark.png',
      idiom: 'universal',
      platform: 'ios',
      size: '1024x1024',
    },
    {
      appearances: [{ appearance: 'luminosity', value: 'tinted' }],
      filename: 'AppIcon-tinted.png',
      idiom: 'universal',
      platform: 'ios',
      size: '1024x1024',
    },
  ],
  info: { author: 'xcode', version: 1 },
};

const DEEP_LINK_COMMENT =
  '<!-- Deep links: reposcout://repo/{owner}/{name} (ADR-0006) -->';

/**
 * bootsplash reformats AndroidManifest.xml and drops its comments; this puts
 * the deep-link note back above the VIEW intent filter (idempotent).
 */
export function restoreManifestComments(manifest: string): string {
  if (manifest.includes(DEEP_LINK_COMMENT)) return manifest;
  return manifest.replace(
    /^([ \t]*)(<intent-filter>\s*<action android:name="android\.intent\.action\.VIEW")/m,
    `$1${DEEP_LINK_COMMENT}\n$1$2`,
  );
}
