/**
 * App version plumbing (ADR-0016): package.json is the single source of truth.
 * Android reads it at build time; iOS and the JS About screen get synced copies.
 */

export const SEMVER = /^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/;

export const GENERATED_VERSION_FILE = 'src/shared/config/version.generated.ts';

export function renderVersionModule(version: string): string {
  return [
    '// Generated by scripts/sync-version.mts from package.json. Do not edit.',
    '// Run `yarn release:prepare <x.y.z>` to change the version (ADR-0016).',
    '',
    `export const APP_VERSION = '${version}';`,
    '',
  ].join('\n');
}

export function setMarketingVersion(pbxproj: string, version: string): string {
  return pbxproj.replace(
    /MARKETING_VERSION = [^;]+;/g,
    `MARKETING_VERSION = ${version};`,
  );
}

export function readMarketingVersions(pbxproj: string): string[] {
  return [...pbxproj.matchAll(/MARKETING_VERSION = ([^;]+);/g)].map(
    m => m[1] ?? '',
  );
}

function readGeneratedVersion(moduleSource: string): string | undefined {
  return /APP_VERSION = '([^']+)'/.exec(moduleSource)?.[1];
}

export function checkVersions(input: {
  packageVersion: string;
  pbxproj: string;
  generatedModule: string | undefined;
}): string[] {
  const { packageVersion, pbxproj, generatedModule } = input;
  const violations: string[] = [];
  if (!SEMVER.test(packageVersion)) {
    violations.push(
      `package.json: "${packageVersion}" is not a semantic version.`,
    );
  }
  const ios = readMarketingVersions(pbxproj);
  if (ios.length === 0 || ios.some(v => v !== packageVersion)) {
    violations.push(
      `ios project: MARKETING_VERSION (${ios.join(', ') || 'none'}) must equal package.json (${packageVersion}).`,
    );
  }
  const generated =
    generatedModule === undefined
      ? undefined
      : readGeneratedVersion(generatedModule);
  if (generated !== packageVersion) {
    violations.push(
      `${GENERATED_VERSION_FILE}: APP_VERSION (${generated ?? 'missing'}) must equal package.json (${packageVersion}).`,
    );
  }
  if (violations.length > 0) {
    violations.push(
      'Fix with `yarn release:prepare <x.y.z>` (or `node scripts/sync-version.mts`).',
    );
  }
  return violations;
}
