/**
 * `yarn arch:graph` — regenerate docs/architecture-graph.md from the real imports
 * (ADR-0022). Slice-level Mermaid graph (GitHub renders it), so the README's
 * architecture picture can't drift from the code.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';

import { cruise } from 'dependency-cruiser';
import extractTSConfig from 'dependency-cruiser/config-utl/extract-ts-config';

import { ROOT } from './lib/repo.mts';

process.chdir(ROOT);

const result = await cruise(
  ['src'],
  {
    outputType: 'mermaid',
    includeOnly: '^src/',
    exclude: { path: ['\\.test\\.tsx?$', '^src/test/'] },
    // One node per slice (src/<layer>/<slice>), or per folder in src/app.
    collapse: '^src/[^/]+/[^/]+',
    tsPreCompilationDeps: true,
    tsConfig: { fileName: 'tsconfig.json' },
  },
  {},
  { tsConfig: extractTSConfig('tsconfig.json') },
);

const mermaid =
  typeof result.output === 'string'
    ? result.output
    : JSON.stringify(result.output);
const target = path.join(ROOT, 'docs', 'architecture-graph.md');
writeFileSync(
  target,
  [
    '# Architecture graph',
    '',
    'Generated by `yarn arch:graph` from the real imports (ADR-0022). Do not edit by hand.',
    'Nodes are slices; arrows point from the importer to what it imports.',
    '',
    '```mermaid',
    mermaid.trim(),
    '```',
    '',
  ].join('\n'),
);
console.log(`Wrote ${path.relative(ROOT, target)}`);
